mqtt:
  sensor:
    - name: "Temperature"
      state_topic: "home/prabhakaran-2025/sensor"
      value_template: "{{ value_json.temperature }}"
      unit_of_measurement: "Â°C"
      device_class: temperature

    - name: "Humidity"
      state_topic: "home/prabhakaran-2025/sensor"
      value_template: "{{ value_json.humidity }}"
      unit_of_measurement: "%"
      device_class: humidity

    - name: "Gas Level"
      state_topic: "home/prabhakaran-2025/sensor"
      value_template: "{{ value_json.gas_level }}"
      unit_of_measurement: "ppm"

default_config:

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
